### ISSUE TITLE
Problem installing the plugin

### ISSUE THREAD

**Issue by alebaiobaio** [AppSaloon/woocommerce-switch-attributes-to-global#2]
Hi there,
I'm having problem installing plugin, it seems that there are some problems with these:
use appsaloon\wcstga\settings\Processor_Settings;
use appsaloon\wcstga\ajax\Product_Ajax;
(new Processor_Settings())->register();
(new Product_Ajax())->register();

Could you help me?

**Comment by aytackokus** [comment]
Hi @alebaiobaio,

What is your problem?

Did you run ``composer install`` via the terminal?

**Comment by alebaiobaio** [comment]
Hi,
Actually I’m tryng to install from backend as I use to do with others plugin



Da: ***@***.***>
Inviato: venerdì 30 aprile 2021 11:37
A: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Oggetto: Re: [AppSaloon/woocommerce-switch-attributes-to-global] Problem installing the plugin (#2)


Hi @alebaiobaio<https://github.com/alebaiobaio>,

What is your problem?

Did you run composer install via the terminal?

**Comment by aytackokus** [comment]
Hi @alebaiobaio,

I just released a version, you can download the complete plugin via this link: https://github.com/AppSaloon/woocommerce-switch-attributes-to-global/releases/download/1.0.4/woocommerce-switch-attributes-to-global.zip

Does this work?

**Comment by alebaiobaio** [comment]
This version is working fine.
Thanks a lto.

Da: ***@***.***>
Inviato: venerdì 30 aprile 2021 12:31
A: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Oggetto: Re: [AppSaloon/woocommerce-switch-attributes-to-global] Problem installing the plugin (#2)


Hi @alebaiobaio<https://github.com/alebaiobaio>,

I just released a version, you can download the complete plugin via this link: https://github.com/AppSaloon/woocommerce-switch-attributes-to-global/releases/download/1.0.4/woocommerce-switch-attributes-to-global.zip

Does this work?

**Comment by aytackokus** [comment]
You are welcome! Don't forget to take a full backup!
