### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by Woutertje** [AppSaloon/woocommerce-switch-attributes-to-global#5]
Hi, thanks for this plugin! Unfortunately i get fatal errors:

Warning: require(/home/*******/public_html/wp-content/plugins/woocommerce-switch-attributes-to-global-master/vendor/autoload.php): failed to open stream: No such file or directory in /home/***********/public_html/wp-content/plugins/woocommerce-switch-attributes-to-global-master/woocommerce-switch-to-global-attributes.php on line 24

Fatal error: require(): Failed opening required '/home/********/public_html/wp-content/plugins/woocommerce-switch-attributes-to-global-master/vendor/autoload.php' (include_path='.:/opt/alt/php74/usr/share/pear') in /home/**************/public_html/wp-content/plugins/woocommerce-switch-attributes-to-global-master/woocommerce-switch-to-global-attributes.php on line 24

Line 24 is "require __DIR__ . '/vendor/autoload.php';" When i Google i read things about composer. Can you tell me what to do? I have like 2000 products to edit so would to get it working. i have shared hosting btw.

**Comment by Woutertje** [comment]
Sorry, just saw the same question already asked... i will find out how to install composer :)

**Comment by aytackokus** [comment]
@Woutertje no problem, were you able to install composer? ;-)

**Comment by Woutertje** [comment]
Thanks for asking, yes it worked like a charm :)
